//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektProgramowanie
{
    using System;
    using System.Collections.Generic;
    
    public partial class adresyZamieszkania
    {
        public string PESEL { get; set; }
        public string miejscowosc { get; set; }
        public string ulica_aleja { get; set; }
        public string nrBudynku { get; set; }
        public string nrMieszkania { get; set; }
        public string kodPocztowy { get; set; }
    
        public virtual klienci klienci { get; set; }
    }
}
