//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektProgramowanie
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjektEntities : DbContext
    {
        public ProjektEntities()
            : base("name=ProjektEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adresyZamieszkania> adresyZamieszkanias { get; set; }
        public virtual DbSet<czynnosci> czynnoscis { get; set; }
        public virtual DbSet<klienci> kliencis { get; set; }
        public virtual DbSet<Klient> Klients { get; set; }
        public virtual DbSet<pracownicy> pracownicies { get; set; }
        public virtual DbSet<samochody> samochodies { get; set; }
        public virtual DbSet<uslugi> uslugis { get; set; }
    }
}
